swagger: '2.0'
info:
  version: '1.0-SNAPSHOT'
  title:
  description:
host: 60.205.205.160:8081
basePath: /Sunflower
schemes:
  - http
paths:

securityDefinitions:
  access_token:
    type: apiKey
    name: Authorization
    in: header
definitions:
    Error:
          required:
            - code
            - message
          properties:
            code:
              type: string
            message:
              type: string
responses:
  Standard500ErrorResponse:
    description: 请求失败
    schema:
      $ref: "#/definitions/Error"
  Standard404ErrorResponse:
    description: 页面不存在
parameters:
  pageSize:
    name: pageSize
    in: query
    description: 每页大小
    type: integer
    format: int32
    required: false
  page:
    in: query
    name: page
    description: 页码
    type: integer
    format: int32
    required: false